In [17]:
#import needed libraries
from sqlalchemy import create_engine
import pandas as pd
import time
from dotenv import dotenv_values

#.env values 
config = dotenv_values('.env')


#get password from environmnet var
uid = config['POSTGRES_USER']
pwd = config['POSTGRES_PASSWORD']
server = "localhost"
db = config['POSTGRES_DB']
port = "5432"


engine = create_engine(f'postgresql://{uid}:{pwd}@{server}:{port}/{db}')

In [18]:
# Reading from Source table 
df = pd.read_sql('Select * from public.customers', engine)
df.head()

,customer_id,company_name,contact_name,contact_title,address,city,region,postal_code,country,phone,fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,None,12209,Germany,030-0074321,030-0076545
1,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,None,05021,Mexico,(5) 555-4729,(5) 555-3745
2,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,None,05023,Mexico,(5) 555-3932,None
3,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,None,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
4,BERGS,Berglunds snabbköp,Christina Berglund,Order Administrator,Berguvsvägen 8,Luleå,None,S-958 22,Sweden,0921-12 34 65,0921-12 34 67

In [ ]:
for index, row in df.iterrows():
    mod = pd.DataFrame(row.to_frame().T)
    mod.to_sql(f"customers_streaming", engine, if_exists='append', index=False)
    print("Row Inserted " + mod.customer_id.astype(str) + ' ' + mod.contact_name.astype(str).astype(str))
    time.sleep(3)